### ISSUE TITLE
Help with a Restkit + CDQ + NSFetchResultsController problem I am facing

### ISSUE THREAD

**Issue by no-itsbackpack** [tillless/restikle#1]
I just saw your post on the Rubymotion Google Group and I wanted to know if you could help me out with an issue am facing. My app works perfectly on the iPhone5/5s/5c but fails on the new devices. I have a link to my post below.
https://groups.google.com/forum/#!topic/rubymotion/uitBOXCoCs8

Thanks in advance

**Comment by matthewsinclair** [comment]
I'm going to close this issue here @paddingtonsbear as it relates more to the use of CoreData than it does to `restikle` in particular. I'll keep watching on the Google Groups to see how it goes.
